// Precompiled Header
#include "Core/Stdafx.h"

#include "Editor/EditorInputMapping.h"

#if GAME_EDITOR_MODE
namespace BH
{
	std::map< Key::KeyCode, CEGUI::Key::Scan > EditorInputMapping::KeyMappingTable = {
		{ Key::A,		  CEGUI::Key::A				},
		{ Key::B,		  CEGUI::Key::B				},
		{ Key::C,		  CEGUI::Key::C				},
		{ Key::D,		  CEGUI::Key::D				},
		{ Key::E,		  CEGUI::Key::E				},
		{ Key::F,		  CEGUI::Key::F				},
		{ Key::G,		  CEGUI::Key::G				},
		{ Key::H,		  CEGUI::Key::H				},
		{ Key::I,		  CEGUI::Key::I				},
		{ Key::J,		  CEGUI::Key::J				},
		{ Key::K,		  CEGUI::Key::K				},
		{ Key::L,		  CEGUI::Key::L				},
		{ Key::M,		  CEGUI::Key::M				},
		{ Key::N,		  CEGUI::Key::N				},
		{ Key::O,		  CEGUI::Key::O				},
		{ Key::P,		  CEGUI::Key::P				},
		{ Key::Q,		  CEGUI::Key::Q				},
		{ Key::R,		  CEGUI::Key::R				},
		{ Key::S,		  CEGUI::Key::S				},
		{ Key::T,		  CEGUI::Key::T				},
		{ Key::U,		  CEGUI::Key::U				},
		{ Key::V,		  CEGUI::Key::V				},
		{ Key::W,		  CEGUI::Key::W				},
		{ Key::X,		  CEGUI::Key::X				},
		{ Key::Y,		  CEGUI::Key::Y				},
		{ Key::Z,		  CEGUI::Key::Z				},
		{ Key::Num0,	  CEGUI::Key::Zero			},
		{ Key::Num1,	  CEGUI::Key::One			},
		{ Key::Num2,	  CEGUI::Key::Two			},
		{ Key::Num3,	  CEGUI::Key::Three			},
		{ Key::Num4,	  CEGUI::Key::Four			},
		{ Key::Num5,	  CEGUI::Key::Five			},
		{ Key::Num6,	  CEGUI::Key::Six			},
		{ Key::Num7,	  CEGUI::Key::Seven			},
		{ Key::Num8,	  CEGUI::Key::Eight			},
		{ Key::Num9,	  CEGUI::Key::Nine			},
		{ Key::Escape,	  CEGUI::Key::Escape		},
		{ Key::LCtrl,	  CEGUI::Key::LeftControl	},
		{ Key::LShift,	  CEGUI::Key::LeftShift		},
		{ Key::LAlt,	  CEGUI::Key::LeftAlt		},
		{ Key::LSystem,   CEGUI::Key::LeftWindows	},
		{ Key::RCtrl,	  CEGUI::Key::RightControl	},
		{ Key::RShift,	  CEGUI::Key::RightShift	},
		{ Key::RAlt,	  CEGUI::Key::RightAlt		},
		{ Key::RSystem,   CEGUI::Key::RightWindows	},
		{ Key::Menu,	  CEGUI::Key::AppMenu		},
		{ Key::LBracket,  CEGUI::Key::LeftBracket	},
		{ Key::RBracket,  CEGUI::Key::RightBracket	},
		{ Key::SemiColon, CEGUI::Key::Semicolon		},
		{ Key::Comma,     CEGUI::Key::Comma			},
		{ Key::Period,    CEGUI::Key::Period		},
		{ Key::Quote,     CEGUI::Key::Apostrophe	},
		{ Key::Slash,     CEGUI::Key::Slash			},
		{ Key::BackSlash, CEGUI::Key::Backslash		},
		{ Key::Tilde,     CEGUI::Key::Grave			},
		{ Key::Equal,     CEGUI::Key::Equals		},
		{ Key::Dash,      CEGUI::Key::Minus			},
		{ Key::Space,	  CEGUI::Key::Space			},
		{ Key::Return,	  CEGUI::Key::Return		},
		{ Key::Back,	  CEGUI::Key::Backspace		},
		{ Key::Tab,		  CEGUI::Key::Tab			},
		{ Key::PageUp,	  CEGUI::Key::PageUp		},
		{ Key::PageDown,  CEGUI::Key::PageDown		},
		{ Key::End,		  CEGUI::Key::End			},
		{ Key::Home,	  CEGUI::Key::Home			},
		{ Key::Insert,	  CEGUI::Key::Insert		},
		{ Key::Delete,	  CEGUI::Key::Delete		},
		{ Key::Add,       CEGUI::Key::Add			},
		{ Key::Subtract,  CEGUI::Key::Subtract		},
		{ Key::Multiply,  CEGUI::Key::Multiply		},
		{ Key::Divide,    CEGUI::Key::Divide		},
		{ Key::Left,      CEGUI::Key::ArrowLeft		},
		{ Key::Right,     CEGUI::Key::ArrowRight	},
		{ Key::Up,        CEGUI::Key::ArrowUp		},
		{ Key::Down,      CEGUI::Key::ArrowDown		},
		{ Key::Numpad0,	  CEGUI::Key::Numpad0		},
		{ Key::Numpad1,	  CEGUI::Key::Numpad1		},
		{ Key::Numpad2,	  CEGUI::Key::Numpad2		},
		{ Key::Numpad3,	  CEGUI::Key::Numpad3		},
		{ Key::Numpad4,	  CEGUI::Key::Numpad4		},
		{ Key::Numpad5,	  CEGUI::Key::Numpad5		},
		{ Key::Numpad6,	  CEGUI::Key::Numpad6		},
		{ Key::Numpad7,	  CEGUI::Key::Numpad7		},
		{ Key::Numpad8,	  CEGUI::Key::Numpad8		},
		{ Key::Numpad9,	  CEGUI::Key::Numpad9		},
		{ Key::F1,		  CEGUI::Key::F1			},
		{ Key::F2,		  CEGUI::Key::F2			},
		{ Key::F3,		  CEGUI::Key::F3			},
		{ Key::F4,		  CEGUI::Key::F4			},
		{ Key::F5,		  CEGUI::Key::F5			},
		{ Key::F6,		  CEGUI::Key::F6			},
		{ Key::F7,		  CEGUI::Key::F7			},
		{ Key::F8,		  CEGUI::Key::F8			},
		{ Key::F9,		  CEGUI::Key::F9			},
		{ Key::F10,		  CEGUI::Key::F10			},
		{ Key::F11,		  CEGUI::Key::F11			},
		{ Key::F12,		  CEGUI::Key::F12			},
		{ Key::F13,		  CEGUI::Key::F13			},
		{ Key::F14,		  CEGUI::Key::F14			},
		{ Key::F15,		  CEGUI::Key::F15			},
		{ Key::Pause,	  CEGUI::Key::Pause			}
	};

	std::map< Mouse::Button, CEGUI::MouseButton > EditorInputMapping::MouseMappingTable = {
		{ Mouse::Left,	  CEGUI::MouseButton::LeftButton	},
		{ Mouse::Middle,  CEGUI::MouseButton::MiddleButton	},
		{ Mouse::Right,	  CEGUI::MouseButton::RightButton	}
	};
}
#endif